### ISSUE TITLE
Error accessing API

### ISSUE THREAD

**Issue by advacom** [hotelbeds-sdk/hotel-api-sdk-php#104] opened 2017-09-29 12:43 UTC
Hello,

Earlier this week I was running into the following issue:

![screen shot 2017-09-25 at 16 44 25](https://user-images.githubusercontent.com/30412911/31016323-7c469644-a524-11e7-9c26-ebc104a35ef8.png)

I contacted your Apitude team and this issue was resolved but resulted in the next issue:
When I'm trying to execute the CheckRates method I'm getting the following error: 

![screen shot 2017-09-28 at 16 01 02](https://user-images.githubusercontent.com/30412911/31016288-5e5ecb60-a524-11e7-86fd-254a1d1d5e33.png)

To be sure it wasn't a error on my behalf I executed the 'BookingConfirm' because I was sure this method was working (Confirmed by Apitude team) before the first error that occurred at the beginning of this week. Unfortunately I'm getting the same error. 

![screen shot 2017-09-28 at 16 34 10](https://user-images.githubusercontent.com/30412911/31016308-7167ffa6-a524-11e7-837c-36f11ce4e471.png)

I've been asked to post the current issue here. This is the ref. Number containing the converstation between me and the Apitude team : #09053727.

Hope you can help me out, 

Thanks in Advance!

**Comment by vmavromatis** [comment] 2017-10-02 07:08
Hi @advacom,

Have you enabled **https** in the endpoint? For example, your HotelApiClient.ini should look like:

```
apiclient.url          = 'https://api.test.hotelbeds.com'
apiclient.apikey       = 'YourApiKeyHere'
apiclient.sharedsecret = 'YourSecretHere'
apiclient.timeout      = '120'
```
Regards

**Comment by advacom** [comment] 2017-10-02 10:35
Hi @vmavromatis,

Thanks for your response. 
I've tried your suggested configurations but they seem to match mine. 

The strange thing is that all was working fine until a colleague of yours changed some settings due to a other and unrelated problem (Destination search not available by default).

From the moment this issue got fixed, the fix produced the above error.

**Comment by vmavromatis** [comment] 2017-10-02 11:06
@advacom, I am checking with my colleague for any potential changes, but in the meantime can you please confirm whether /demo/availability.php executes fine for you (given that you change the details in the .ini file of the /demo/ folder)? Please note that by default availability.php runs a hotels array request (as opposed to destination/geolocation). This way we can identify whether it's a setup/network issue or something else.

Thank you in advance.

**Comment by advacom** [comment] 2017-10-02 14:13
Hi @vmavromatis, The availability executes fine. It returns me two hotels and all the rooms that are available.

Hope you could help us out.

Thanks

**Comment by vmavromatis** [comment] 2017-10-02 15:33
Hi, @advacom we're looking into the possiblity that this issue is server-side related. Can you kindly show me the Availability and Booking requests and responses (4 total)? The most important bit is the booking response.

You can capture this if you debug booking.php and put a breaking point inside the catch method where $apiClient is. From there you may grab lastRawRequest and lastRawResponse from inside httpClient as in the picture below:
 
![image](https://user-images.githubusercontent.com/8668731/31085318-101182f2-a797-11e7-81fd-4591b7b3ab6c.png)

Alternatively, you may just put in the [error log as shown here.](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/wiki/How-to-deal-with-'500-Internal-Server-Error')

Thank you in advance.

**Comment by advacom** [comment] 2017-10-04 15:04
Hi @vmavromatis,

I'm only able to retrieve the availability request and response. 
When trying to fetch the booking it already breaks on the error i've send to you.
See logs below:


[response_availability.log](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/1356290/response_availability.log)
[request_availability.log](https://github.com/hotelbeds-sdk/hotel-api-sdk-php/files/1356291/request_availability.log)

Thanks for helping out.

**Comment by vmavromatis** [comment] 2017-10-04 15:30
@advacom , thank you for your response and the logs.

I was able to reproduce the error which happens at booking (error code: SYSTEM_ERROR-Cxxxxxxxxx) and have escalated it to the appropriate team for what appears to be a server related issue. 
For this reason, I will be now closing this current ticket, as the issue appears to be unrelated to the SDK.
Please feel free to follow case #09053727 and I will be monitoring the situation as well. 

Should you run into any problems with the SDK please open a new ticket. Thank you and apologies I could not be of any further assistance.

**Closed by vmavromatis** 2017-10-04 15:30 UTC
Labels: bug, Server-side related

**Comment by advacom** [comment] 2017-10-05 06:59
Hi @vmavromatis, Thanks for your help. Where does this casenumber relate to? Where can I see the progress. Thanks again.

**Comment by vmavromatis** [comment] 2017-10-05 07:10
@advacom, It is the case number you mentioned in your first post. You should keep using the same method of contact.

**Comment by advacom** [comment] 2017-10-05 07:14
Allright thanks, is it possible to see this log by browser?

**Comment by vmavromatis** [comment] 2017-10-05 07:33
Unfortunately not. The best you can do is try to catch the exception, in a way similar to the one I described above. For example in this case I was able to capture the following:


```
--------------------------BOOKING RQ---------------------------------------------

{
  "holder": {
    "name": "IntegrationTestFirstName",
    "surname": "IntegrationTestLastName"
  },
  "rooms": [{
    "rateKey": "20171118|20171119|W|197|218356|DBL.ST|ST_ES|HS|674|1~1~0||N@BD1DCDDB8A8F4649AFE3FB0D970DADC31741",
    "paxes": [{
      "roomId": "1",
      "type": "AD",
      "name": "Adult Name"
    }]
  }],
  "clientReference": "IntegrationAgency"
}

--------------------------BOOKING RS---------------------------------------------
{
    "auditData": {
        "processTime": "426",
        "timestamp": "2017-10-02 17:42:53.656",
        "requestHost": "212.170.239.110",
        "serverId": "sa37AUX3ROLBLIS.env#PL",
        "environment": "[int]",
        "release": "ca31ed999397d4426c4902df6e482b2460a84f9a",
        "token": "b3e58aef-2920-489e-945e-1c4884f168a9",
        "internal": "0|BD1DCDDB8A8F4649AFE3FB0D970DADC31741|ES|01|6|232|||||||||||S|9|1|1~1~1~0||0||0|xwx7b9mxcufw542tmkjanc9a||"
    },
    "error": {
        "code": "SYSTEM_ERROR-C36C459695FD426FB139FFBA2551FC4A",
        "message": "Internal server error"
    }
}
```

As you can see an Internal Server Error is caused with a code "SYSTEM_ERROR-C36C459695FD426FB139FFBA2551FC4A". This code needed to be communicated to apitude@hotelbeds.com so they can look into it.
Alternatively you may use a tool like [Postman](https://app.getpostman.com/run-collection/be1769748a078faef0b1#?env%5BAPItude%20portal%20environment.template%5D=W3siZW5hYmxlZCI6dHJ1ZSwia2V5IjoiZW5kcG9pbnQiLCJ2YWx1ZSI6Imh0dHBzOi8vYXBpLnRlc3QuaG90ZWxiZWRzLmNvbS8iLCJ0eXBlIjoidGV4dCJ9LHsiZW5hYmxlZCI6dHJ1ZSwia2V5IjoiQXBpLWtleSIsInZhbHVlIjoiWFhYWFhYWFhYWFhYWCIsInR5cGUiOiJ0ZXh0In0seyJlbmFibGVkIjp0cnVlLCJrZXkiOiJTZWNyZXQiLCJ2YWx1ZSI6IlhYWFhYWFhYWCIsInR5cGUiOiJ0ZXh0In1d).

**Comment by advacom** [comment] 2017-10-05 07:41
Thats clear thanks. 
We will wait a bit for an update. Can you see if this error is only within the test environment or if it is also within the production environment? 

Thanks again, you have been very helpfull.

**Comment by vmavromatis** [comment] 2017-10-05 08:41
This APIkey only has access to the test environment which is an exact clone of the live environment, so a similar behavior should be expected in both.

No problem, glad to be of help.

**Comment by advacom** [comment] 2017-10-09 10:30
Hello @vmavromatis,

Can you see if there is any progress fixing the above issues?
Hope to hear from you. 

Thanks

**Comment by vmavromatis** [comment] 2017-10-09 10:57
I just checked, the development team is currently looking into it, as part of the current sprint. If I'm not wrong, it seems to be affecting specifically Disney-related hotels, which at least narrows down the issue.

In the meantime, you might want to try another API-key, just in case that the issue is API-key related?

**Comment by vmavromatis** [comment] 2017-10-26 11:43
@advacom Just so you know, this issue should be getting patched today at 15:00 CEST. Hope this helps. Let me know if you run into any issues using the SDK.

**Comment by advacom** [comment] 2017-10-31 07:42
@vmavromatis Thanks for your update. I've been told by the API team that the update only have been run on the live environment and that we had to wait 2-3 week for the update to be active on the test environment. Isn't there a way to speed this up? Continue on a different version of the testenvironment?

Thanks for your help again.

**Comment by vmavromatis** [comment] 2017-11-02 09:13
@advacom, I asked the API team whether this is possible. Usually INT environment gets cloned from LIVE in fixed intervals. I'm afraid these are the only 2 public environments, all else is private and older versions don't get published either.

Apologies for any inconvenience, I will see if there is anything I can do.
