### ISSUE TITLE
Live environment return no data

### ISSUE THREAD

**Issue by nathanphan** [hotelbeds-sdk/hotel-api-sdk-php#119] opened 2018-02-01 08:00 UTC
POST https://api.hotelbeds.com/hotel-api/1.0/hotels
body:
`{
  "stay": {
    "checkIn": "2018-02-01",
    "checkOut": "2018-02-03",
    "shiftDays": "2"
  },
  "occupancies": [
    {
      "rooms": 1,
      "adults": 1,
      "children": 0
    }
  ],
  "hotels": {
    "hotel": [ 1, 271, 24739
,24740
,24741
,24742
,24743
,53574
,53580
,79670
,79671
,79672
,79673
,79674
,79676
,79770]
  },
  "filter": {
        "minRate": 100.000, 
        "maxRate": 1700.000,
        "minCategory": 3,
        "maxCategory": 5,
        "paymentType": "AT_HOTEL",
        "maxRatesPerRoom": 3,
        "packaging": true,
        "hotelPackage": "YES"
    } 
}`

Response:

`{
    "auditData": {
        "processTime": "4",
        "timestamp": "2018-02-01 08:57:28.156",
        "requestHost": "88.157.202.165, 176.34.239.206",
        "serverId": "ip-10-185-27-57.node.liveaws.discovery#PL",
        "environment": "[liveaws]",
        "release": "38a2a13f4c5c4d87218b24e225722c809168b85f",
        "token": "8fc22959-3bff-4b39-88a0-5d844fad20fd",
        "internal": "0||VN|06|0|0|3,5||||-100.000,1700.000|Y|AT_HOTEL|||||0||1~1~1~0||0||0|j4c52xdcy64wzwupfagn64hc|||"
    },
    "hotels": {
        "total": 0
    }
}`

it is same for other hotel codes

**Comment by vmavromatis** [comment] 2018-02-03 09:57
Hi @nathanphan.
This is not related to the SDK so I'm tagging it as Server-side related. Are you still getting this issue? I checked your key and it seems to be configured fine.

**Comment by nathanphan** [comment] 2018-02-04 04:15
Maybe the server was down. After a couple of hours, it responsed well. Just wonder why there is no email a status page to talk about it. Anyway please close this issue. Thanks a lot

**Comment by vmavromatis** [comment] 2018-02-05 08:08
Glad it's solved, yes, we will add a status page in the future. Closing the issue.

**Closed by vmavromatis** 2018-02-05 08:08 UTC
Labels: Server-side related

**Comment by Defunktt1** [comment] 2018-03-05 13:08
Now I have the same issue. Someone has this trouble too?

**Comment by vmavromatis** [comment] 2018-03-05 14:36
@Defunktt1 Can you please share your Availability Request? I can try to reproduce. Also, it might just mean that the requested hotels have no availability on those dates. Try removing some filters and see if you get any results. 

I hope this helps.

**Comment by Defunktt1** [comment] 2018-03-05 15:30
This is my availability [request](https://gist.github.com/Defunktt1/44f7162f7e439fda5275c84f02e4224e).
This codes is all my hotels in database in Madrid.
I changed the date for April and changed the city to another (NYC, ODS) and got "hotels": {"total": 0}. I tryed make requst via SDK and via APITUDE.

**Comment by vmavromatis** [comment] 2018-03-05 15:51
@Defunktt1 I tried running your request and it's working fine for me - I get a result on LIVE. Can you please pass my your apikey (NOT secret)? I can check if it's configured OK.

**Comment by Defunktt1** [comment] 2018-03-05 15:54
4hegmwg2ufwjj9mr5btqy5en
Pre-production version

**Comment by vmavromatis** [comment] 2018-03-05 16:32
Yes, I checked and there is indeed a problem with the INT environment (to which pre-production is linked) returning 0 availability. The product team is working to resolve this ASAP. Apologies for any inconvenience.

**Comment by Defunktt1** [comment] 2018-03-05 17:14
Thank you hor help.
