### ISSUE TITLE
Empty response in a booking function 

### ISSUE THREAD

**Issue by becology1100** [hotelbeds-sdk/hotel-api-sdk-php#105] opened 2017-10-02 11:49 UTC
Hi,  i was trying to make a book throw the booking function but i got an empty response

thisa is my code 

$reader = new Zend\Config\Reader\Ini();
$commonConfig   = $reader->fromFile('/home/hoscobeds/public_html/hotelbedsAPI/vendor/common.ini');
$currentEnvironment = $commonConfig["environment"]? $commonConfig["environment"]: "DEFAULT";
$environmentConfig   = $reader->fromFile('/home/hoscobeds/public_html/hotelbedsAPI/vendor/hotelbeds/hotel-api-sdk-php/tests/config/Environment.' . strtoupper($currentEnvironment) . '.ini');
$cfgApi = $commonConfig["apiclient"];
$cfgUrl = $environmentConfig["url"];

$apiClient = new HotelApiClient($cfgUrl["default"],
    $cfgApi["apikey"],
    $cfgApi["sharedsecret"],
    new ApiVersion(ApiVersions::V1_0),
    $cfgApi["timeout"],
    null,
    $cfgUrl["secure"]);

    $rateKey = urldecode($_GET['rateKey']);
    $paxes = [ new Pax(Pax::AD, 30, "Mike", "Doe", 1), new Pax(Pax::AD, 27, "Jane", "Doe", 1), new Pax(Pax::CH, 8, "Mack", "Doe", 1) ];

    $rqBookingConfirm = new \hotelbeds\hotel_api_sdk\helpers\Booking();
    $rqBookingConfirm->holder = new \hotelbeds\hotel_api_sdk\model\Holder("Hotelbeds", "PHP_IS_FUN");
    $rqBookingConfirm->language="ENG";
    $bookingRoom = new \hotelbeds\hotel_api_sdk\model\BookingRoom($rateKey);
    $bookingRoom->paxes = $paxes;
    $bookRooms[] = $bookingRoom;
    $rqBookingConfirm->rooms = $bookRooms;
    $rqBookingConfirm->clientReference = "PHP_DEMO";
    $apiClient->BookingConfirm($rqBookingConfirm);

    print_r($confirmRS->booking);
 
thanks

**Comment by vmavromatis** [comment] 2017-10-02 13:19
Hi @becology1100, thank you for using the SDK. A few issues here:
As per [the documentation](https://developer.hotelbeds.com/docs/read/apitude_booking/Booking_Confirmation), you have to define version 1.2 (not 1.0) when booking **without** a credit card. I'm writing this first, because it's a common mistake.

Another concern is that you are printing `confirmRS ` which you have not defined, unless it's somewhere further up and I'm not seeing it (for example here you probably need to do `$confirmRS = $apiClient->BookingConfirm($rqBookingConfirm);` Lastly, I'm not entirely sure how you are passing your GET variable, if it's similar to the demo (url encoded) there should be no problem. 
Does your IDE complain about any errors? I assume you have loaded the libraries.

All in all I would suggest you edited the 2nd to last line into:
`$confirmRS = $apiClient->BookingConfirm($rqBookingConfirm);`

I hope this helps, but if not, feel free to let me know and I will try to reproduce again.

**Comment by vmavromatis** [comment] 2017-10-05 08:59
@becology1100, I will be closing this issue now. Feel free to re-open if you have any more questions.

**Closed by vmavromatis** 2017-10-05 08:59 UTC
