### ISSUE TITLE
php_network_getaddresses

### ISSUE THREAD

**Issue by djaney** [hotelbeds-sdk/hotel-api-sdk-php#77] opened 2017-03-22 10:51 UTC
I am suddenly getting this error for a previously working code:
```
Error accessing API: Unable to connect to api.test.hotelbeds.com:443 . Error #0: stream_socket_client(): unable to connect to api.test.hotelbeds.com:443 (php_network_getaddresses: getaddrinfo failed: Name or service not known)
```

I am using nginx and php-fpm 7.0 in my local.
I already ruled out my network because I can connect to the API using curl just fine.

Any ideas?

**Comment by Zavierazo** [comment] 2017-03-22 11:09
Hi @djaney can you share your HotelApiClient.ini with the secret deleted? I will check if all is correct.

**Comment by djaney** [comment] 2017-03-22 14:03
I did not use ini since I need them dynamic. This is how initialized the client. This is using latest version btw.
```
$this->client = new HotelApiClient("https://api.test.hotelbeds.com", "4gxjqgeyttvu2jn63bnnbpn4", "xxxxxxxxx", new ApiVersion(ApiVersions::V1_0), $timeout);
```

**Comment by langocthach** [comment] 2017-06-13 03:07
I have same problem. Did you find the reason cause it @djaney ?
Thanks.

**Comment by djaney** [comment] 2017-06-13 11:54
@langocthach no, not yet

**Comment by vmavromatis** [comment] 2017-09-11 16:14
Hi @djaney & @langocthach, unfortunately I am unable to reproduce the bug. Your dynamic initialization of the client should work fine. Can you please try a simple availability request for hotel codes as following and let me know if you are still getting the same error? Just paste this code right after your initialization line:

```
$rqData = new \hotelbeds\hotel_api_sdk\helpers\Availability();
$rqData->stay = new Stay(DateTime::createFromFormat("Y-m-d", "2018-03-01"),
    DateTime::createFromFormat("Y-m-d", "2018-03-10"));

$rqData->hotels = [ "hotel" => [ 1067, 1070, 1506 ] ];
$occupancy = new Occupancy();
$occupancy->adults = 2;
$occupancy->children = 1;
$occupancy->rooms = 1;

$occupancy->paxes = [ new Pax(Pax::AD, 30, "Mike", "Doe"), new Pax(Pax::AD, 27, "Jane", "Doe"), new Pax(Pax::CH, 8, "Mack", "Doe") ];
$rqData->occupancies = [ $occupancy ];

try {
    $availRS = $apiClient->Availability($rqData);
} catch (\hotelbeds\hotel_api_sdk\types\HotelSDKException $e) {
    $auditData = $e->getAuditData();
    error_log( $e->getMessage() );
    error_log( "Audit remote data = ".json_encode($auditData->toArray()));
    exit();
} catch (Exception $e) {
    error_log( $e->getMessage() );
    exit();
}

// Check availability is empty or not!
if (!$availRS->isEmpty()) {
    var_dump($availRS->hotels->toArray());
} else {
    echo "There are no results!";
}
```

**Comment by vmavromatis** [comment] 2017-09-18 10:09
As I was unable to reproduce the error I will be closing the issue. From the looks of it, this issue appears to be a DNS error, hence the  _Name or service not known_. Please make sure that your DNS resolves properly or that no firewall is blocking the connection. 

If you need more help or guidance, please feel free to re-open.

**Closed by vmavromatis** 2017-09-18 10:09 UTC
